"""empty message

Revision ID: b13fe03741e5
Revises: af0ab7536e6c
Create Date: 2021-11-07 20:18:45.043769

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b13fe03741e5"
down_revision = "af0ab7536e6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comments_timestamp", table_name="comments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_comments_timestamp", "comments", ["timestamp"], unique=False)
    # ### end Alembic commands ###
